### PR TITLE
Add support for Centos and rsyslog versions <= 6.x

### PR DESCRIPTION
**Pull request by alboyadjian**
Leveraged some values already set in a platform-specific way by the rsyslog cookbook to ensure correct group permissions and working directories for Centos (should work for all RHEL).

Added support for the rsyslog config syntax for versions 6.x and lower.

### CODE REVIEW

**Comment by squaresurf** [comment]
This is looking good. I'd love to see updates to kitchen as well so that it's easy to make sure these work with centos and ubuntu via kitchen. I'll see if I can get to it soon.

**Comment by alboyadjian** [comment]
Does someone have time to review this or https://github.com/spartansystems/spartan_loggly_rsyslog-cookbook/pull/7 ?

It's been working pretty well for me on both ubuntu and rhel.  The code in https://github.com/spartansystems/spartan_loggly_rsyslog-cookbook/pull/7 is a lot cleaner, but it adds a feature that might not be of interest.  If that's the case, I can update this branch with the useful code-cleanup features from the other branch.  

Alternately, instead of this ugly hack to try to detect the rsyslog version, I can do as you suggested in the comments on https://github.com/spartansystems/spartan_loggly_rsyslog-cookbook/pull/5 and just have the target rsyslog version specified as an attribute.

I've got time right now to work on this, but that won't be true for much longer, so please try and get back to me soon.

**Comment by squaresurf** [comment]
I like the approach that you have in #7.

**Comment by squaresurf** [comment]
I will leave my comments there. Feel free to close this PR when you're ready and we can work through some other items on #7.

Thank you for all your hard work!

**Pull request closed without merging**
