### PR TITLE
Removes deprecated `Statefile`.

### PR DESCRIPTION
**Pull request by maraca**
`Statefile` has been deprecated with Rsyslog 8.0.

### CODE REVIEW

**Comment by squaresurf** [comment]
@maraca have to tested to see if that works for you with Rsyslog 8?

What do you think about adding a rsyslog version attribute that can be 7 or 8 and will allow us to be backwards compatible?

If so, I'd love to make sure we also have test coverage for the scenarios when the version is 7, 8, or some version not supported. The tests can be written in chefspec.

Thank you again for diving into this.

**Comment by squaresurf** [comment]
@maraca are you still interested in working with this? If not, I **might** be able to work on this a bit soon. It is looking like we should support Rsyslog versions 6 - 8 initially as you can see #6 adds support for version <= 6.

**Comment by maraca** [comment]
Hey @squaresurf. Yes still interested however I'm not sure when I will have time to get on it :\

**Comment by dfish9** [comment]
Abandoned PR, closing

**Pull request closed without merging**
