### PR TITLE
Update node attribute access to fix deprecation warning.

### PR DESCRIPTION
**Pull request by alboyadjian**
This shows up when doing a chef run as:

> Deprecated features used!
>   method access to node attributes (node.foo.bar) is deprecated and will
>   be removed in Chef 13, please use bracket syntax (node["foo"]["bar"])  at 30 locations:

As much as I love the dot-syntax, I'd rather have this work in chef 13.

### CODE REVIEW

**Review by squaresurf — CHANGES_REQUESTED** [review]
I agree with this. Looks like you may have missed a few locations though.

```
grep -PR '(node|default)\.' . --color
Binary file ./.git/index matches
./libraries/loggly_helpers.rb:    node.default['loggly']['rsyslog_major_version'] = version_for_platform || 7
./README.md:  node.set.loggly.log_files = [
./README.md:  node.default['loggly']['apps'] = {
./spec/recipes/default_spec.rb:      node.set.loggly.token = token
./spec/recipes/default_spec.rb:      node.normal.rsyslog.priv_group = rsyslog_group
./spec/recipes/default_spec.rb:    expect(chef_run.node.rsyslog.max_message_size).to eq '64k'
./spec/recipes/default_spec.rb:    expect(chef_run.node.loggly.rsyslog.port).to eq port
./spec/recipes/default_spec.rb:    expect(chef_run.node.loggly.rsyslog.host).to eq host
./spec/recipes/default_spec.rb:        node.set.loggly.token = token
./spec/recipes/default_spec.rb:        node.set.loggly.tags = tags
./spec/recipes/default_spec.rb:        node.set.loggly.token = token
./spec/recipes/default_spec.rb:        node.set.loggly.log_files = files
./spec/recipes/default_spec.rb:        node.set.loggly.token = token
./spec/recipes/default_spec.rb:        node.set.loggly.log_files = files
./spec/recipes/default_spec.rb:        node.set.loggly.token = token
./spec/recipes/default_spec.rb:        node.set.loggly.token = token
./spec/recipes/default_spec.rb:      node.set.loggly.token = token
./spec/recipes/default_spec.rb:    expect(chef_run.node.loggly.rsyslog_major_version).to eq(5)
./spec/recipes/default_spec.rb:      node.set.loggly.token = token
./spec/recipes/default_spec.rb:    expect(chef_run.node.loggly.rsyslog_major_version).to eq(7)
./spec/recipes/default_spec.rb:      node.set.loggly.token = token
./spec/recipes/default_spec.rb:    expect(chef_run.node.loggly.rsyslog_major_version).to eq(7)
./spec/recipes/default_spec.rb:      node.set.loggly.token = token
./spec/recipes/default_spec.rb:    expect(chef_run.node.loggly.rsyslog_major_version).to eq(8)
```

**Comment by alboyadjian** [comment]
Addressed in dba9321

The recipe-based setters (node.default and node.set) don't get changed to node['default'] and node['set'].

**Review by squaresurf — APPROVED** [review]
:clap:

**Comment by squaresurf** [comment]
Thank you @vhladama!

**Comment by squaresurf** [comment]
I just released version `3.1.1` that should include these fixes.

**Comment by alboyadjian** [comment]
Glad to hear it.

Are there any other TODO items?

I was thinking of adding a feature for adding a config file to do Ruby on Rails logging.

**Comment by squaresurf** [comment]
I don't think we have any TODO items at this point in time. Please open a new issue to discuss the RoR logging.

You could also look at the other issues we have open.

**Pull request merged**
